### ISSUE TITLE
Support calls from the gate-cloud plugin.

### ISSUE THREAD

**Issue by sodre** [zeroae/zae-lambda-java-gate#24]
As a GateDeveloper user I would like to use the [GATECloud client plugin][cloud-client] to make calls the Lambda GATE endpoints.

To support this use-case we need to conform to the [client API][client-api].

  - [x] Compare Content-Type of `cloud.gate.ac.uk` and the one supported by `gate.zeroae.co`
  - [x] Change *default* response type to `application/json` #30 
  - [x] Support response types 
    - [x] `application/json` #25
    - [x] `application/gate+xml`  #25
    - [x] `application/fastinfoset` #25
  - [x] Return Error [messages][read-error] as JSON with "message" field.  #27
  - [x] Don't break if additional Accept content-type options are passed. #28 
  - [x] Support *optional* parameter `includeText=no` in the response type. #31 
    - [x] `application/gate+xml; includeText=no`
    - [x] `application/fastinfoset; includeText=no` 
  - [x] Handle [nextAnnotationId][next-id] #33 
  - [x] Support controlling Annotation Selectors. #34 
  - [x] Support the `/metadata` endpoint [[1][metadata.xml]]. #36 It should return data that looks like this
    ```xml
    <metadata>
        <name>annie-named-entity-recognizer</name>
        <defaultAnnotations>:Address, :Date, :Location, :Organization, :Person</defaultAnnotations>
        <additionalAnnotations>:Money, :Percent, :Token, :SpaceToken, :Sentence</additionalAnnotations>
        <costPerRequest>10</costPerRequest>
        <dailyQuota>1000</dailyQuota>
    </metadata>
    ``` 
    ```yaml
    {
        "name": "annie-named-entity-recognizer",
        "defaultAnnotations": ":Address, :Date, :Location, :Organization, :Person",
        "additionalAnnotations": ":Money, :Percent, :Token, :SpaceToken, :Sentence",
        "costPerRequest": 10,
        "dailyQuota": 1000
     }
     ```

[cloud-client]: https://github.com/GateNLP/cloud-client/wiki/Gate-Plugin
[client-api]: https://github.com/GateNLP/cloud-client/blob/master/library/src/main/java/uk/ac/gate/cloud/online/ApiEndpoint.java
[read-error]: https://github.com/GateNLP/cloud-client/blob/345bc4709739348ce77d1c7b0d26dfac276f0500/library/src/main/java/uk/ac/gate/cloud/client/RestClient.java#L418-L447
[next-id]: https://github.com/GateNLP/cloud-client/blob/345bc4709739348ce77d1c7b0d26dfac276f0500/gate-plugin/src/main/java/uk/ac/gate/cloud/pr/GateCloudPR.java#L237-L242
[metadata.xml]: https://cloud.gate.ac.uk/info/help/package-example.html#section-3.

**Comment by sodre** [comment]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1043285/110742979-4fc9ba80-8205-11eb-835c-cc201ec6d215.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/1043285/110743101-80115900-8205-11eb-89c0-858dceaed361.png">

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/1043285/110743258-c49cf480-8205-11eb-96ae-8f23ff1886c4.png">

**Comment by sodre** [comment]
Closed in 0.7.0
